spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: pagamento.exchange  # Adicione esta linha para configurar a exchange padrão

app:
  rabbitmq:
    queues:
      criado: pagamento.criado.queue  # Nome da fila como variável de configuração
      deletado: pagamento.deletado.queue

pedido-service:
  base-url: http://localhost:8084/pedido

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.tcc.pedido_service: DEBUG