spring:
  rabbitmq:
    host: rabbitmq  # Nome do serviço no docker-compose
    port: 5672
    username: guest
    password: guest
    template:
      exchange: pagamento.exchange
    listener:
      simple:
        retry:
          enabled: true  # Habilita retry automático para falhas
          max-attempts: 3
          initial-interval: 2000ms

app:
  rabbitmq:
    queues:
      pedido-criado: pagamento.criado.queue  # Fila para pedidos criados
      pedido-processado: pagamento.processado.queue  # Fila para respostas
    routing-keys:
      pedido-criado: pedido.criado  # Routing key para eventos de pedido